### ISSUE TITLE
Errors with jruby 1.7.19 on Windows

### ISSUE THREAD

**Issue by Daikamar** [djberg96/sys-filesystem#15]
On Windows 7
Rails 3.2.5
Including sys-filesystem in the Gemfile causes problems with most everything reporting a need for jruby-win32ole even though jruby-win32ole gem is installed:

```
C:\Programming\RubyMine\steve\stevetest>rake --tasks
io/console not supported; tty will not be manipulated
!!!! Missing jruby-win32ole gem: jruby -S gem install jruby-win32ole
rake aborted!
LoadError: no such file to load -- jruby-win32ole
C:/Programming/RubyMine/steve/stevetest/config/application.rb:7:in `(root)'
C:/Programming/RubyMine/steve/stevetest/rakefile:1:in `(root)'
C:/Programming/RubyMine/steve/stevetest/rakefile:5:in `(root)'
c:\jruby-1.7.19\bin\rake:23:in `(root)'
(See full trace by running task with --trace)
```

Pounding out the req for sys-filesystem fixes the issue.

```
*** LOCAL GEMS ***

actionmailer (3.2.5)
actionpack (3.2.5)
activemodel (3.2.5)
activerecord (3.2.5)
activerecord-jdbc-adapter (1.3.15)
activerecord-jdbcpostgresql-adapter (1.3.15)
activeresource (3.2.5)
activesupport (3.2.5)
arel (3.0.3)
builder (3.0.4)
bundler (1.9.2)
coffee-rails (3.2.2)
coffee-script (2.3.0)
coffee-script-source (1.9.1)
daemon_controller (1.2.0)
daemons (1.2.2)
dalli (2.7.4)
delayed_job (3.0.5)
delayed_job_active_record (4.0.3)
erubis (2.7.0)
execjs (2.4.0)
ffi (1.9.8 java, 1.9.3 java)
hike (1.2.3)
i18n (0.7.0)
jar-dependencies (0.1.2)
jdbc-postgres (9.4.1200)
journey (1.0.4)
jquery-rails (3.1.2, 3.0.4)
jquery-ui-rails (4.1.2)
jruby-openssl (0.9.6 java, 0.9.5 java)
jruby-pageant (1.1.1 java)
jruby-win32ole (0.8.5)
json (1.8.2 java, 1.8.0 java)
krypt (0.0.2)
krypt-core (0.0.2 universal-java)
krypt-provider-jdk (0.0.2)
mail (2.4.4)
mime-types (1.25.1)
multi_json (1.11.0)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (2.9.2)
polyglot (0.3.5)
rack (1.4.5)
rack-cache (1.2)
rack-ssl (1.3.4)
rack-test (0.6.3)
rails (3.2.5)
railties (3.2.5)
rake (10.4.2, 10.1.0)
rdoc (4.1.2, 3.12.2)
sass (3.4.13)
sass-rails (3.2.6)
sprockets (2.1.4)
sys-filesystem (1.1.4)
therubyrhino (2.0.4)
therubyrhino_jar (1.7.4)
thor (0.19.1)
tilt (1.4.1)
treetop (1.4.15)
tzinfo (0.3.43)
uglifier (2.7.1)
will_paginate (3.0.7)
```

**Comment by djberg96** [comment]
I'm confused, do I need to explicitly add jruby-win32ole as a dependency?

**Comment by Daikamar** [comment]
You already do in lib/windows/sys/filesystem.rb (line 6)
I get the above error despite having the win32ole gem installed

**Comment by Daikamar** [comment]
Here's full trace if that helps:

```
C:\Programming\RubyMine\steve\stevetest>rake --tasks --trace
io/console not supported; tty will not be manipulated
!!!! Missing jruby-win32ole gem: jruby -S gem install jruby-win32ole
rake aborted!
LoadError: no such file to load -- jruby-win32ole
org/jruby/RubyKernel.java:1071:in `require'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency
'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
C:/jruby-1.7.19/lib/ruby/shared/jruby/win32ole/stub.rb:3:in `(root)'
org/jruby/RubyKernel.java:1071:in `require'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency
'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/sys-filesystem-1.1.4/lib/windows/sys/filesystem.rb:1:in `(root)'
org/jruby/RubyKernel.java:1071:in `require'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency
'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/sys-filesystem-1.1.4/lib/windows/sys/filesystem.rb:6:in `(root)'
org/jruby/RubyKernel.java:1071:in `require'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/sys-filesystem-1.1.4/lib/sys/filesystem.rb:1:in `(root)'
org/jruby/RubyArray.java:1613:in `each'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/sys-filesystem-1.1.4/lib/sys/filesystem.rb:2:in `(root)'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/bundler-1.9.2/lib/bundler/runtime.rb:1:in `(root)'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/bundler-1.9.2/lib/bundler/runtime.rb:85:in `require'
org/jruby/RubyKernel.java:1071:in `require'
C:/jruby-1.7.19/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/bundler-1.9.2/lib/bundler/runtime.rb:61:in `require'
org/jruby/RubyKernel.java:1087:in `load'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/bundler-1.9.2/lib/bundler.rb:134:in `require'
C:/Programming/RubyMine/steve/stevetest/config/application.rb:7:in `(root)'
C:/Programming/RubyMine/steve/stevetest/rakefile:1:in `(root)'
C:/Programming/RubyMine/steve/stevetest/rakefile:5:in `(root)'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/rake_module.rb:1:in `(root)'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:94:in `load_rakefile'
C:/jruby-1.7.19/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
org/jruby/RubyKernel.java:1087:in `load'
c:\jruby-1.7.19\bin\rake:23:in `(root)'
```

**Comment by djberg96** [comment]
I meant a dependency in the gemspec. I'm not sure what you meant by "pounding out the req" either. A bundle install?

**Comment by Daikamar** [comment]
Yes installed via bundle. By "pounding out the req" I mean commenting out sys-filesystem in the Gemfile resolves the issue. So on a brand new rails project you get:

With "gem 'sys-filesystem'" in Gemfile
```
C:\Programming\RubyProjects\steve\stevetest>rake --tasks
io/console not supported; tty will not be manipulated
!!!! Missing jruby-win32ole gem: jruby -S gem install jruby-win32ole
rake aborted!
LoadError: no such file to load -- jruby-win32ole
C:/Programming/RubyProjects/steve/stevetest/config/application.rb:7:in `(root)'
C:/Programming/RubyProjects/steve/stevetest/rakefile:1:in `(root)'
C:/Programming/RubyProjects/steve/stevetest/rakefile:5:in `(root)'
c:\jruby-1.7.19\bin\rake:23:in `(root)'
(See full trace by running task with --trace)
```

With "#gem 'sys-filesystem'" in Gemfile
```
C:\Programming\RubyProjects\steve\stevetest>rake --tasks
io/console not supported; tty will not be manipulated
rake about              # List versions of all Rails frameworks and the env...
rake assets:clean       # Remove compiled assets
rake assets:precompile  # Compile all the assets named in config.assets.pre...
rake db:create          # Create the database from config/database.yml for ...
rake db:drop            # Drops the database for the current Rails.env (use...
rake db:fixtures:load   # Load fixtures into the current environment's data...
rake db:migrate         # Migrate the database (options: VERSION=x, VERBOSE...
rake db:migrate:status  # Display status of migrations
rake db:rollback        # Rolls the schema back to the previous version (sp...
rake db:schema:dump     # Create a db/schema.rb file that can be portably u...
rake db:schema:load     # Load a schema.rb file into the database
rake db:seed            # Load the seed data from db/seeds.rb
rake db:setup           # Create the database, load the schema, and initial...
rake db:structure:dump  # Dump the database structure to db/structure.sql
rake db:version         # Retrieves the current schema version number
rake doc:app            # Generate docs for the app -- also available doc:r...
rake log:clear          # Truncates all *.log files in log/ to zero bytes
rake middleware         # Prints out your Rack middleware stack
rake notes              # Enumerate all annotations (use notes:optimize, :f...
rake notes:custom       # Enumerate a custom annotation, specify with ANNOT...
rake rails:template     # Applies the template supplied by LOCATION=(/path/...
rake rails:update       # Update configs and some other initially generated...
rake routes             # Print out all defined routes in match order, with...
rake secret             # Generate a cryptographically secure secret key (t...
rake stats              # Report code statistics (KLOCs, etc) from the appl...
rake test               # Runs test:units, test:functionals, test:integrati...
rake test:recent        # Run tests for {:recent=>"test:prepare"} / Test re...
rake test:single        # Run tests for {:single=>"test:prepare"}
rake test:uncommitted   # Run tests for {:uncommitted=>"test:prepare"} / Te...
rake time:zones:all     # Displays all time zones, also available: time:zon...
rake tmp:clear          # Clear session, cache, and socket files from tmp/ ...
rake tmp:create         # Creates tmp directories for sessions, cache, sock...
```

**Comment by djberg96** [comment]
I'm afraid this is some sort of environment issue on your end, or a Rails issue. Works fine for me.
