### ISSUE TITLE
Clash with mkmf gem

### ISSUE THREAD

**Issue by Neil-Aframe** [djberg96/sys-filesystem#24]
For some reason that I do not understand, the ```sys-filesystem``` gem require appears sensitive to the require order when ```mkmf``` standard lib is used in the same project.  When required *before* mkmf, there is no *apparent* problem (although I am concerned there might be a hidden problem with same root cause). When required *after* mkmf, I get an ```ArgumentError```

I can replicate this in ```irb``` for Ruby 2.1.4 (Mac OS/X):

```
$ irb
2.1.4 :001 > require 'mkmf'
 => true
2.1.4 :002 > require 'sys/filesystem'
ArgumentError: wrong number of arguments (1 for 2+)
	from /Users/neilslater/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/mkmf.rb:1213:in `find_type'
	from /Users/neilslater/.rvm/gems/ruby-2.1.4/gems/ffi-1.9.14/lib/ffi/struct.rb:332:in `find_type'
	from /Users/neilslater/.rvm/gems/ruby-2.1.4/gems/ffi-1.9.14/lib/ffi/struct.rb:326:in `find_field_type'
	from /Users/neilslater/.rvm/gems/ruby-2.1.4/gems/ffi-1.9.14/lib/ffi/struct.rb:368:in `array_layout'
	from /Users/neilslater/.rvm/gems/ruby-2.1.4/gems/ffi-1.9.14/lib/ffi/struct.rb:278:in `layout'
	from /Users/neilslater/.rvm/gems/ruby-2.1.4/gems/sys-filesystem-1.1.7/lib/sys/unix/sys/filesystem/structs.rb:34:in `<class:Statfs>'
	from /Users/neilslater/.rvm/gems/ruby-2.1.4/gems/sys-filesystem-1.1.7/lib/sys/unix/sys/filesystem/structs.rb:7:in `<module:Structs>'
	from /Users/neilslater/.rvm/gems/ruby-2.1.4/gems/sys-filesystem-1.1.7/lib/sys/unix/sys/filesystem/structs.rb:6:in `<class:Filesystem>'
	from /Users/neilslater/.rvm/gems/ruby-2.1.4/gems/sys-filesystem-1.1.7/lib/sys/unix/sys/filesystem/structs.rb:5:in `<module:Sys>'
	from /Users/neilslater/.rvm/gems/ruby-2.1.4/gems/sys-filesystem-1.1.7/lib/sys/unix/sys/filesystem/structs.rb:4:in `<top (required)>'
	from /Users/neilslater/.rvm/gems/ruby-2.1.4/gems/sys-filesystem-1.1.7/lib/sys/unix/sys/filesystem.rb:2:in `require_relative'
	from /Users/neilslater/.rvm/gems/ruby-2.1.4/gems/sys-filesystem-1.1.7/lib/sys/unix/sys/filesystem.rb:2:in `<top (required)>'
	from /Users/neilslater/.rvm/gems/ruby-2.1.4/gems/sys-filesystem-1.1.7/lib/sys/filesystem.rb:11:in `require_relative'
	from /Users/neilslater/.rvm/gems/ruby-2.1.4/gems/sys-filesystem-1.1.7/lib/sys/filesystem.rb:11:in `<top (required)>'
	from /Users/neilslater/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/neilslater/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/neilslater/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from (irb):2
	from /Users/neilslater/.rvm/rubies/ruby-2.1.4/bin/irb:11:in `<main>'
```

I have also replicated this on Ruby 2.1.4 on Debian, and latest Ruby 2.3.1 on Mac OS/X.

**Comment by djberg96** [comment]
Interesting. This isn't an issue with sys-filesystem in particular:

```
# mkmf_conflict.rb
require 'mkmf'
require 'ffi'

module Foo
  class Bar
    class Baz < FFI::Struct
      layout(:alpha, :int)
    end
  end
end
```
```
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/2.3.0/mkmf.rb:1237:in `find_type': wrong number of arguments (given 1, expected 2+) (ArgumentError)
	from /Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/struct.rb:332:in `find_type'
	from /Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/struct.rb:326:in `find_field_type'
	from /Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/struct.rb:368:in `array_layout'
	from /Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/struct.rb:278:in `layout'
	from mkmf_conflict.rb:7:in `<class:Baz>'
	from mkmf_conflict.rb:6:in `<class:Bar>'
	from mkmf_conflict.rb:5:in `<module:Foo>'
	from mkmf_conflict.rb:4:in `<main>'
```
The last time I checked mkmf doesn't namespace any of its methods, so my guess is that there's a conflict between it and FFI. The mkmf "library" is not really meant to be used as a library for any sort of scripting or programming in the traditional sense, and the source code is atrocious.

Generally speaking I would not try to mix mkmf with any other library. If you need something that *is* designed to be used as a library, please checkout my *mkmf-lite* library.

**Comment by Neil-Aframe** [comment]
Thanks for getting back to me. Seems like someone added `mkmf` to a shared project just for the method `find_executable0` - I think I can resolve that with a replacement.

**Comment by djberg96** [comment]
@Neil-Aframe I don't remember what that method does right off, but if it's something that can be added to mkmf-lite, please put in a feature request there.

**Comment by Neil-Aframe** [comment]
Thanks, I found and tested using ptools `File.which` in place or `find_executable0` around same time as you making the suggestion. Problem solved!
