### ISSUE TITLE
`attach_function': Function 'getmntinfo64' not found in [libc.dylib] (FFI::NotFoundError)

### ISSUE THREAD

**Issue by rgaufman** [djberg96/sys-filesystem#48]
There seem to be an issue with Apple Silicon machines:

```
Romans-MacBook-Air.local ➜  TestApp git:(master) ✗ bundle exec rails c
/opt/homebrew/lib/ruby/gems/2.7.0/bundler/gems/ffi-2b44904f8323/lib/ffi/library.rb:273:in `attach_function': Function 'getmntinfo64' not found in [libc.dylib] (FFI::NotFoundError)
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys/unix/sys/filesystem/functions.rb:44:in `rescue in <module:Functions>'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys/unix/sys/filesystem/functions.rb:29:in `<module:Functions>'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys/unix/sys/filesystem/functions.rb:5:in `<class:Filesystem>'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys/unix/sys/filesystem/functions.rb:4:in `<module:Sys>'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys/unix/sys/filesystem/functions.rb:3:in `<main>'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys/unix/sys/filesystem.rb:3:in `<main>'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys/filesystem.rb:13:in `<main>'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
```

**Comment by djberg96** [comment]
All I can tell is that on Catalina it's exported. On my box libc.dylib links to libSystem.dylib, and using otool to show a list of cached libraries, I ultimately found it in /usr/lib/system/libsystem_c.dylilb:

`otool -L /usr/lib/libSystem.dylib`

```
>nm -a /usr/lib/system/libsystem_c.dylib | grep mnt  
0000000000078f94 T _getmntinfo
00000000000272e9 T _getmntinfo$INODE64
000000000008dfa8 b _getmntinfo$INODE64.vars
000000000008fc30 b _getmntinfo.vars
0000000000064ea0 T _getmntinfo64
000000000008fbf0 b _getmntinfo64.bufsize
000000000008fbe0 b _getmntinfo64.mntbuf
000000000008fbe8 b _getmntinfo64.mntsize
000000000002730f t _getmntinfo_internal
0000000000078fba t _getmntinfo_internal
0000000000079083 T _getmntinfo_r_np
00000000000273d8 T _getmntinfo_r_np$INODE64
```

What Silicon does I'm not sure. You could try and find it by iterating over all the .dylib's under /usr/lib and see if you can find it:

```
Dir["/usr/lib/system/*.dylib"].each do |file|
  nm = `nm -a #{file} | grep mnt`
  if nm.size > 0
    p file
    p nm
  end
end
```

**Comment by rgaufman** [comment]
The above code returns this:

```
Romans-MacBook-Air.local ➜  ~  irb
irb(main):001:1* Dir["/usr/lib/system/*.dylib"].each do |file|
irb(main):002:1*   nm = `nm -a #{file} | grep mnt`
irb(main):003:2*   if nm.size > 0
irb(main):004:2*     p file
irb(main):005:2*     p nm
irb(main):006:1*   end
irb(main):007:0> end
=> ["/usr/lib/system/libsystem_pthread.dylib", "/usr/lib/system/libsystem_kernel.dylib", "/usr/lib/system/libsystem_platform.dylib"]
```

**Comment by rgaufman** [comment]
Also:

```
Romans-MacBook-Air.local ➜  ~  nm -a /usr/lib/system/libsystem_pthread.dylib | grep mnt
Romans-MacBook-Air.local ➜  ~  nm -a /usr/lib/system/libsystem_kernel.dylib | grep mnt
Romans-MacBook-Air.local ➜  ~  nm -a /usr/lib/system/libsystem_platform.dylib | grep mnt
```

**Comment by rgaufman** [comment]
Here is gripping for info:

```
Romans-MacBook-Air.local ➜  ~  nm -a /usr/lib/system/libsystem_*.dylib | grep -i info
00000000000284d4 T ___channel_get_info
00000000000285c4 T ___coalition_info
0000000000002594 T ___proc_info
0000000000028d94 T ___proc_info_extended_id
000000000001ce24 T __kernelrpc_mach_port_dnrequest_info
000000000001d8ec T __kernelrpc_mach_port_space_basic_info
000000000001cc48 T __kernelrpc_mach_port_space_info
0000000000013854 T _coalition_info_resource_usage
00000000000138bc T _coalition_info_set_efficiency
0000000000013888 T _coalition_info_set_name
0000000000016ec0 T _host_get_boot_info
0000000000005d1c T _host_info
000000000001a580 T _host_lockgroup_info
0000000000019cd8 T _host_processor_info
0000000000019fd4 T _host_virtual_physical_table_info
0000000000029a58 T _kas_info
0000000000019e68 T _kmod_get_info
0000000000004e84 T _kpersona_info
0000000000015e0c T _kpersona_pidinfo
000000000001af74 T _mach_memory_info
0000000000015ad4 T _mach_port_dnrequest_info
000000000001593c T _mach_port_space_basic_info
0000000000015938 T _mach_port_space_info
00000000000016c4 T _mach_timebase_info
000000000003c6ac s _mach_timebase_info.cached_info
00000000000013e4 T _mach_timebase_info_trap
000000000001f124 T _mach_vm_page_info
0000000000028214 T _mach_voucher_debug_info
000000000001a6fc T _mach_zone_info
000000000001b3ec T _mach_zone_info_for_largest_zone
000000000001b294 T _mach_zone_info_for_zone
0000000000011428 t _os_channel_info2attr
0000000000011718 T _os_channel_read_nexus_extension_info
0000000000007644 T _posix_spawnattr_getmacpolicyinfo_np
00000000000076b8 t _posix_spawnattr_macpolicyinfo_lookup
000000000000771c T _posix_spawnattr_setmacpolicyinfo_np
000000000000eedc T _proc_piddynkqueueinfo
000000000000ee74 T _proc_pidfdinfo
000000000000eea8 T _proc_pidfileportinfo
0000000000002560 T _proc_pidinfo
0000000000007eb0 T _proc_pidoriginatorinfo
000000000000ef10 T _proc_udata_info
000000000002076c T _processor_info
00000000000201d8 T _processor_set_info
0000000000024154 T _task_get_dyld_image_infos
0000000000001a3c T _task_info
0000000000023da0 T _task_map_corpse_info
000000000002465c T _task_map_corpse_info_64
0000000000023740 T _task_purgable_info
0000000000023ee4 T _task_register_dyld_image_infos
00000000000242d0 T _task_register_dyld_shared_cache_image_info
000000000000a7c0 T _task_set_info
000000000002401c T _task_unregister_dyld_image_infos
0000000000022970 T _task_zone_info
0000000000007cf8 T _thread_info
                 U _mach_timebase_info
0000000000005250 T _platform_thread_info
                 U _task_info
                 U _thread_info
                 U ___proc_info
                 U _host_info
                 U _thread_info
```

**Comment by djberg96** [comment]
So it looks like they're not exporting it. Why? Not sure. Maybe they forgot. Maybe they changed the API. If it's the latter, I'll need some guidance. Does the man page for it show anything?

`man getmntinfo`

**Comment by djberg96** [comment]
Maybe I'm supposed to be using `getmntinfo_r_np` instead, but it still doesn't look like it's exported on your system.

**Comment by rgaufman** [comment]
Seems that man page hasn't been updated in a while. Strange, maybe it is a bug, I'll try to report to Apple.

```
GETMNTINFO(3)            BSD Library Functions Manual            GETMNTINFO(3)

NAME
     getmntinfo getmntinfo_r_np getmntinfo64 -- get information about mounted file systems

SYNOPSIS
     #include <sys/param.h>
     #include <sys/ucred.h>
     #include <sys/mount.h>

     int
     getmntinfo(struct statfs **mntbufp, int flags);

     int
     getmntinfo_r_np(struct statfs **mntbufp, int flags);

TRANSITIIONAL SYNOPSIS (NOW DEPRECATED)
     int
     getmntinfo64(struct statfs64 **mntbufp, int flags);

DESCRIPTION
     The getmntinfo() function returns an array of statfs structures describing each currently mounted file system (see statfs(2)).  As statfs(2) indicates, the
     structure is defined differently depending on whether the macro _DARWIN_FEATURE_64_BIT_INODE is defined (see stat(2) for more information on this macro).

     The getmntinfo() and getmntinfo_r_np() functions pass their flags argument transparently to getfsstat(2).

     The getmntinfo() function maintains ownership of the results buffer it allocates, and may overwrite or free this buffer in subsequent calls to
     getmntinfo().  For this reason, getmntinfo() is not thread-safe.

     The getmntinfo_r_np() function is a thread-safe equivalent of getmntinfo() that allocates a new results buffer on every call and transfers ownership of
     this buffer to the caller.  The caller is responsible for freeing this memory with free(3).

RETURN VALUES
     On successful completion, getmntinfo() and getmntinfo_r_np() return a count of the number of elements in the array.  The pointer to the array is stored
     into mntbufp.

     If an error occurs, zero is returned and the external variable errno is set to indicate the error.  The getmntinfo() function may modify the mbtbufp
     pointer even in the case of an error.  In this situation, callers should consider any previous information returned by getmntinfo() to be lost.  The
     getmntinfo_r_np() function will not modify the mntbufp pointer in the case of an error.

ERRORS
     The getmntinfo() and getmntinfo_r_np() functions may fail and set errno for any of the errors specified for the library routines getfsstat(2) or malloc(3).

TRANSITIONAL DESCRIPTION (NOW DEPRECATED)
     The getmntinfo64() routine is equivalent to its corresponding non-64-suffixed routine, when 64-bit inodes are in effect.  It was added before there was
     support for the symbol variants, and so is now deprecated.  Instead of using it, set the _DARWIN_USE_64_BIT_INODE macro before including header files to
     force 64-bit inode support.

     The statfs64 structure used by this deprecated routine is the same as the statfs structure when 64-bit inodes are in effect.

SEE ALSO
     getfsstat(2), mount(2), stat(2), statfs(2), mount(8)

HISTORY
     The getmntinfo() function first appeared in 4.4BSD.  The getmntinfo_r_np() function first appeared in macOS 10.13.

BUGS
     The getmntinfo() function writes the array of structures to an internal static object and returns a pointer to that object.  Subsequent calls to
     getmntinfo() will modify the same object.

     The memory allocated by getmntinfo() cannot be free(3)'d by the application.

BSD                             April 12, 2017                             BSD
```

**Comment by djberg96** [comment]
@rgaufman Can you please paste the output of `uname -a`?

**Comment by rgaufman** [comment]
```
Romans-MacBook-Air.local ➜  Tether  uname -a
Darwin Romans-MacBook-Air.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101 arm64
```

**Comment by djberg96** [comment]
Possible clue from https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes:

New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

I'll have to dig into FFI now to see what I can do. That, or switch everything to Fiddle.

**Comment by rgaufman** [comment]
Did you have any luck? - I believe this is the last dependency in my rails app preventing me to use native code :)

**Comment by djberg96** [comment]
@rgaufman I'm afraid not, I simply don't know what the answer is. As I have no plans to upgrade to Big Sur at this point (I have privacy concerns), I will be entirely reliant on PR's for this.

**Comment by martinsp** [comment]
I did some investigation regarding the issue. The man page for `getmntinfo` has the following section

> TRANSITIONAL DESCRIPTION (NOW DEPRECATED)
>      The getmntinfo64() routine is equivalent to its corresponding non-64-suffixed routine, when 64-bit inodes are in effect.  It was added before there was
>      support for the symbol variants, and so is now deprecated.  Instead of using it, set the _DARWIN_USE_64_BIT_INODE macro before including header files to
>      force 64-bit inode support.
> 
>      The statfs64 structure used by this deprecated routine is the same as the statfs structure when 64-bit inodes are in effect.

It looks like on M1 because it's 64 bit only, the `getmntinfo64` is not available, and only the `getmntinfo` exists

I used the following program to check the existance of `getmntinfo*` in `libc.dylib`

<details>
<summary>lib-check.c file</summary>

```c
// compile with: clang ./lib-check.c -o lib-check
// run: ./lib-check

#include <stdio.h>
#include <dlfcn.h>

void check_fn(void * lib_handle, char* fn_name);

int main(int argc, char **argv) { 
    void * libc_handle = dlopen("libc.dylib", RTLD_LAZY);
    if (libc_handle == NULL) {
        printf("libc could not be opened\n");
        return 1;
    }

    printf("libc opened\n");
    check_fn(libc_handle, "getmntinfo");
    check_fn(libc_handle, "getmntinfo64");
}

void check_fn(void* lib_handle, char* fn_name) {
    void * fn_address = dlsym(lib_handle, fn_name);
    if (fn_address == NULL) {
        printf("Function not found: %s\n", fn_name);
    } else {
        printf("Function found: %s\n", fn_name);
    }
}
```

</details>

Output on M1 Mac mini
```
$ uname -a
Darwin Martinss-Mac-mini.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64

$ ./lib-check 
libc opened
Function found: getmntinfo
Function not found: getmntinfo64
```

Output on MacBook Pro
```
$ uname -a
Darwin mpbox-2.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
$ ./lib-check
libc opened
Function found: getmntinfo
Function found: getmntinfo64
```

Changing line https://github.com/djberg96/sys-filesystem/blob/c2b939d75702385a70acd2638298cf8c340205eb/lib/sys/unix/sys/filesystem/functions.rb#L44 to `attach_function(:getmntinfo, [:pointer, :int], :int)` fixes the issue on M1. Looks like the code needs additional check for M1 macs?

**Comment by djberg96** [comment]
What happens if you apply this diff?

```
diff --git a/lib/sys/unix/sys/filesystem/functions.rb b/lib/sys/unix/sys/filesystem/functions.rb
index 953c927..4769a4a 100644
--- a/lib/sys/unix/sys/filesystem/functions.rb
+++ b/lib/sys/unix/sys/filesystem/functions.rb
@@ -41,7 +41,11 @@ module Functions
         end
       rescue FFI::NotFoundError
         if RbConfig::CONFIG['host_os'] =~ /darwin|osx|mach/i
-          attach_function(:getmntinfo, :getmntinfo64, [:pointer, :int], :int)
+          begin
+            attach_function(:getmntinfo, :getmntinfo64, [:pointer, :int], :int)
+          rescue FFI::NotFoundError
+            attach_function(:getmntinfo, [:pointer, :int], :int) # Big Sur and later
+          end
         else
           attach_function(:getmntinfo, [:pointer, :int], :int)
         end
```

**Comment by martinsp** [comment]
The patch works. Also the test suite runs successfully with `rake spec` when the patch is applied.

**Comment by djberg96** [comment]
Alright, I've pushed out 1.4.1 which should address the issue then. Thanks for testing for me.

**Comment by radiospiel** [comment]
Thanks everyone! Just stumbled across this and am really glad you looked into it an d fixed that.
