### ISSUE TITLE
'Failed to compile' error at runtime when missing build environment

### ISSUE THREAD

**Issue by zarqman** [djberg96/sys-filesystem#76]
Seeing the error below on v1.5.2 in production (works fine in 1.4.5; haven't tried 1.5.[01]).

The affected app runs inside a docker container. That container is built using separate build and runtime images. In the somewhat common pattern, the build image includes gcc and friends, but the runtime image does not. Gems are installed using the build image, and all compiled artifacts copied over to the smaller runtime image.

The stack trace makes me think it's trying to compile at runtime instead of during the gem's install, which is a bit unexpected for a gem (assuming I'm interpreting it correctly). Thoughts?

```
/usr/local/bundle/gems/mkmf-lite-0.7.1/lib/mkmf/lite.rb:238:in `block in try_to_execute': Failed to compile source code with command 'gcc -lrt -ldl -lcrypt -lm  -o conftest.exe conftest.c': (RuntimeError)
===
#include <stdio.h>
#include <stdio.h>
#include <stdlib.h>
int conftest_const = (int)(sizeof(int));
int main(){
printf("%d\n", conftest_const);
return 0;
}
===
from /usr/local/bundle/gems/mkmf-lite-0.7.1/lib/mkmf/lite.rb:216:in `chdir'
from /usr/local/bundle/gems/mkmf-lite-0.7.1/lib/mkmf/lite.rb:216:in `try_to_execute'
from /usr/local/bundle/gems/mkmf-lite-0.7.1/lib/mkmf/lite.rb:166:in `check_sizeof'
from /usr/local/bundle/gems/memoist-0.16.2/lib/memoist.rb:213:in `check_sizeof'
from /usr/local/bundle/gems/sys-filesystem-1.5.2/lib/sys/unix/sys/filesystem/structs.rb:249:in `<class:Statvfs>'
from /usr/local/bundle/gems/sys-filesystem-1.5.2/lib/sys/unix/sys/filesystem/structs.rb:151:in `<module:Structs>'
from /usr/local/bundle/gems/sys-filesystem-1.5.2/lib/sys/unix/sys/filesystem/structs.rb:8:in `<class:Filesystem>'
from /usr/local/bundle/gems/sys-filesystem-1.5.2/lib/sys/unix/sys/filesystem/structs.rb:7:in `<module:Sys>'
from /usr/local/bundle/gems/sys-filesystem-1.5.2/lib/sys/unix/sys/filesystem/structs.rb:6:in `<top (required)>'
from /usr/local/bundle/gems/sys-filesystem-1.5.2/lib/sys/unix/sys/filesystem.rb:2:in `require_relative'
from /usr/local/bundle/gems/sys-filesystem-1.5.2/lib/sys/unix/sys/filesystem.rb:2:in `<top (required)>'
from /usr/local/bundle/gems/sys-filesystem-1.5.2/lib/sys/filesystem.rb:8:in `require_relative'
from /usr/local/bundle/gems/sys-filesystem-1.5.2/lib/sys/filesystem.rb:8:in `<top (required)>'
from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
```

**Comment by djberg96** [comment]
You should be able to use 1.5.1. There was a recent change in 1.5.2 where I was trying to cope yet another 32 vs 64 bit issue. You can see it at https://github.com/djberg96/sys-filesystem/pull/73, with original discussion at https://github.com/djberg96/sys-filesystem/issues/71.

I wondered if this would cause issues. Ideas welcome.
