### ISSUE TITLE
Failure/Error: require 'sys/filesystem'  Errno::ETXTBSY:   Text file busy - ./conftest.exe

### ISSUE THREAD

**Issue by aramprice** [djberg96/sys-filesystem#77]
I haven't yet come up with a smaller reproduction of the error. An example of it failing in Github Actions is here:
- https://github.com/cloudfoundry/bosh/actions/runs/11172203909/job/31058286335?pr=2572#step:7:44

For some reason the Github action does not show the same stack trace we see in our internal CI which I've included below.

My first hunch was that this had something to do with our use of https://rubygems.org/gems/parallel_tests but I haven't been able to reproduce with those two gems.

It may also have to do with many/multiple loading of files, there are warnings about this in our test output. I'm working on fixing those issues separately in hopes that the problem we're having with `sys-filesystem` go away. I'll update this issue if there's anything of interest.

Draft PR in our repo with the update:
- https://github.com/cloudfoundry/bosh/pull/2572

```
Failure/Error: require 'sys/filesystem'

Errno::EACCES:
  Permission denied - ./conftest.exe
# /usr/local/bundle/ruby/3.3.0/gems/mkmf-lite-0.7.1/lib/mkmf/lite.rb:232:in `block in try_to_execute'
# /usr/local/bundle/ruby/3.3.0/gems/mkmf-lite-0.7.1/lib/mkmf/lite.rb:216:in `chdir'
# /usr/local/bundle/ruby/3.3.0/gems/mkmf-lite-0.7.1/lib/mkmf/lite.rb:216:in `try_to_execute'
# /usr/local/bundle/ruby/3.3.0/gems/mkmf-lite-0.7.1/lib/mkmf/lite.rb:166:in `check_sizeof'
# /usr/local/bundle/ruby/3.3.0/gems/memoist-0.16.2/lib/memoist.rb:213:in `check_sizeof'
# /usr/local/bundle/ruby/3.3.0/gems/sys-filesystem-1.5.2/lib/sys/unix/sys/filesystem/structs.rb:249:in `<class:Statvfs>'
# /usr/local/bundle/ruby/3.3.0/gems/sys-filesystem-1.5.2/lib/sys/unix/sys/filesystem/structs.rb:151:in `<module:Structs>'
# /usr/local/bundle/ruby/3.3.0/gems/sys-filesystem-1.5.2/lib/sys/unix/sys/filesystem/structs.rb:8:in `<class:Filesystem>'
# /usr/local/bundle/ruby/3.3.0/gems/sys-filesystem-1.5.2/lib/sys/unix/sys/filesystem/structs.rb:7:in `<module:Sys>'
# /usr/local/bundle/ruby/3.3.0/gems/sys-filesystem-1.5.2/lib/sys/unix/sys/filesystem/structs.rb:6:in `<top (required)>'
# /usr/local/bundle/ruby/3.3.0/gems/sys-filesystem-1.5.2/lib/sys/unix/sys/filesystem.rb:2:in `require_relative'
# /usr/local/bundle/ruby/3.3.0/gems/sys-filesystem-1.5.2/lib/sys/unix/sys/filesystem.rb:2:in `<top (required)>'
# /usr/local/bundle/ruby/3.3.0/gems/sys-filesystem-1.5.2/lib/sys/filesystem.rb:8:in `require_relative'
# /usr/local/bundle/ruby/3.3.0/gems/sys-filesystem-1.5.2/lib/sys/filesystem.rb:8:in `<top (required)>'
# ./lib/bosh/director/api/api_helper.rb:1:in `<top (required)>'
# ./lib/bosh/director/api.rb:8:in `<top (required)>'
# ./lib/bosh/director.rb:37:in `<top (required)>'
# ./spec/support/task_helpers.rb:1:in `<top (required)>'
# ./spec/spec_helper.rb:21:in `block in <top (required)>'
# ./spec/spec_helper.rb:21:in `each'
# ./spec/spec_helper.rb:21:in `<top (required)>'
# ./spec/unit/cpi_config/parsed_cpi_config_spec.rb:1:in `<top (required)>'
```

**Comment by djberg96** [comment]
Yeah, I think I'm going to have to unroll the changes for 1.5.2, too many issues doing runtime compiler checks.

**Comment by aramprice** [comment]
Cool, thanks for the attention! Let me know if there's any other info that might be helpful.

**Comment by djberg96** [comment]
1.5.3 is released. Please give it a try.

**Comment by aramprice** [comment]
That fixed our issue, thank you!

https://github.com/cloudfoundry/bosh/actions/runs/11172946133/job/31060211951?pr=2572#step:7:98
